### ISSUE TITLE
@submit 이벤트 핸들러의 form 객체에 checkbox, textarea 값이 전달되지 않음

### ISSUE THREAD

**Issue by ibare** [woowabros/WoowahanJS#12]
```Javascript
events: {
  '@submit form': 'onSubmit'
},

onSubmit(form) { ... }
```

 onSubmit 핸들러의 form 객체에 checkbox 와 textarea 값이 정상적으로 전달되지 않음

* checkbox: checked, unchecked 와 상관없이 항상 checked 상태의 값이 전달됨
* textarea 요소는 포함되지 못함

**Comment by woowa** [comment]
https://github.com/woowabros/WoowahanJS/commit/d45c7635bc21cf3fd03dde062ed69c2e6a0ff5e0
