### ISSUE TITLE
라우팅 변경 시 탐지 방법

### ISSUE THREAD

**Issue by flyskyne** [woowabros/WoowahanJS#21]
안녕하세요.

라우팅 변경 전이나 후에 탐지할 수 있는 방법에 대해 마련되어 있지 않은 것 같아서..
router.js의 라우팅 콜백 함수 내에서 app에 route 이벤트를 발생시키도록 해 보면 괜찮을 것 같은데요.
woowahan.js의 Router.design()을 호출하는 부분에 this를 넘겨야 할 것 같긴 하지만요.

이게 필요한 이유가.. 로그인 상태에 따라서 특정 뷰에 접근을 제한하고 싶은 니즈가 있습니다.
이벤트 핸들러에서 라우팅 변경을 허용한다든지 거부할 수 있으면 좋겠고
혹은 promise를 반환하여 promise 결과에 따라 계속 진행한다든지 하면 좋을 것 같은데요.

현재는 레이아웃 뷰의 viewWillUnmount()에서 처리토록 하였는데 이것보단 라우팅 변경을 탐지할 수 있는 수단이 제공되면 좋을 것 같습니다.

**Comment by ibare** [comment]
오늘 릴리즈한 v0.3.0에 추가된 미들웨어를 이용하시면 더 효과적일 것이라 생각합니다.
다음 문서를 참고하시면 작성하실 수 있을 듯 합니다. 아직 내용이 충실하지 못한데요. 곧 보충이 될 예정입니다.
https://ibare.gitbooks.io/woowahanjs/middleware.html
