### ISSUE TITLE
Woowahan.View 변수에 대한 naming convention

### ISSUE THREAD

**Issue by prorhap** [woowabros/WoowahanJS#23]
프로젝트에 설정된 WoowahanJS 소스와 이곳 Git에 정리된 예제들에서 사용한 변수명 naming convention에 의문이 있습니다. (convention이 맞지 않다고 인지함)

Woowahan.View에 대한 인스턴스 변수는 github에 정리된 예제를 보면 다음과 같이 camel case를 사용하는데, WoowahanJS내 코드를 보면 pascal case를 사용하고 있습니다. 

`const emptyView = Woowahan.View.create('EmptyView');`

어떤 convention을 권장하는지 궁금합니다.

**Comment by ibare** [comment]
기본 적으로 낙타법을 따르고 있습니다. View 의 이름이나 기타 식별자 등에 대한 컨벤션을 강하게 가이드하고 있지는 않고요, 가이드 한다고 해도 실제 앱을 만드는 프로젝트의 컨벤션이 우선이라고 생각하고 있습니다.
