### ISSUE TITLE
링크 깨짐 문의

### ISSUE THREAD

**Issue by chanwook00** [woowabros/WoowahanJS#24]
안녕하세요. 
우아한JS를 공부하고 있습니다.
레퍼런스를 보는 중에 깨진 링크가 있어 신고&문의 드립니다. 

페이지 위치 : https://ibare.gitbooks.io/woowahanjs/view.html 
메뉴 : View > 템플릿 > '프로젝트 환경 구성' 링크깨짐 
깨진링크 : https://ibare.gitbooks.io/woowahanjs/project-setup.md 

이상입니다. 수고하세요~

**Comment by woowa** [comment]
링크 수정 했습니다.
감사합니다.
