### ISSUE TITLE
woowahanjs 1 대 버전과 woowahan-action-player 같이 사용하는 경우 성능문제

### ISSUE THREAD

**Issue by ghost** [woowabros/WoowahanJS#27]
1. 현상
woowahanjs 1대 버전에서 woowahan-action-player를 import 하여 app.use(actionPlayer) 주입을 하는 경우에(직접 페이지에서 action-player를 사용하지 않아도) 페이지의 리스트가 커텐이 내려오듯 스르륵 하고 랜더링 되는 현상 데이터 개수가 많고 적음에 관계없이 현상이 발생함

2. 짐작되는 원인
준호님께서 woowahan-action-player가 추가 되고 미들웨어 처리부분과 관련이 있을 거라고 짐작함

**Comment by woowa** [comment]
`woowahan-action-player`를 자바였더니 리스트가 스까무는거죠? 확인할께요. :)

**Comment by woowa** [comment]
새로운 버전으로 테스트 해주세요.
