### ISSUE TITLE
woowahanjs 1 대 버전에서 리스트 데이터를 랜더링 할 경우 깜빡 거리는 현상

### ISSUE THREAD

**Issue by ghost** [woowabros/WoowahanJS#28]
1.현상
woowahanjs 1대 버전에서 콜렉션(배열)을 랜더링 하여 리스팅 할때 화면이 비었다가 리스트가 랜더링 되어 나타나는 현상, 배열의 개수가 적을 때는 유심히 보아야 알아 차릴 수 있지만 많아지면 흰색(비어있는)화면이 눈에 선명하게 보인후
데이터 리스트가 랜더링되어 리스팅됨 깜빡 거리는 느낌으로 랜더링됨

2.짐작되는 원인
개발자도구 퍼포먼스 탭에서 살펴본 결과로는 미들웨어를 처리하는 부분에서 로드가 많이 걸리는 것으로 나타났음
(새로 추가한 미들웨어는 없는 상태에서 woowahanjs 1대 버전에서 발생)

**Comment by woowa** [comment]
새로운 버전으로 테스트해 주세요.
